
[target.thumbv7m-none-eabi]

# uncomment ONE of these three option to make `cargo run` start a GDB session
# which option to pick depends on your system
#runner = "probe-run --chip stm32f103C8"
#runner = "probe-run --chip stm32f103C6"
runner = "probe-run --chip stm32f103VE"
# runner = "probe-run --chip stm32f103C8 --connect-under-reset"
# runner = "arm-none-eabi-gdb -q -x openocd.gdb"
# runner = "gdb-multiarch -q -x openocd.gdb"
# runner = "gdb -q -x openocd.gdb"

rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=--nmagic"]

[build]
target = "thumbv7m-none-eabi"